package org.nterlearning.datamodel.catalog.model;

import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FlagReportStats service. Represents a row in the &quot;CATALOG_FlagReportStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.nterlearning.datamodel.catalog.model.impl.FlagReportStatsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.nterlearning.datamodel.catalog.model.impl.FlagReportStatsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FlagReportStats
 * @see org.nterlearning.datamodel.catalog.model.impl.FlagReportStatsImpl
 * @see org.nterlearning.datamodel.catalog.model.impl.FlagReportStatsModelImpl
 * @generated
 */
public interface FlagReportStatsModel extends AttachedModel,
    BaseModel<FlagReportStats> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a flag report stats model instance should use the {@link FlagReportStats} interface instead.
     */

    /**
     * Returns the primary key of this flag report stats.
     *
     * @return the primary key of this flag report stats
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this flag report stats.
     *
     * @param primaryKey the primary key of this flag report stats
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the flag report stats ID of this flag report stats.
     *
     * @return the flag report stats ID of this flag report stats
     */
    public long getFlagReportStatsId();

    /**
     * Sets the flag report stats ID of this flag report stats.
     *
     * @param flagReportStatsId the flag report stats ID of this flag report stats
     */
    public void setFlagReportStatsId(long flagReportStatsId);

    /**
     * Returns the fully qualified class name of this flag report stats.
     *
     * @return the fully qualified class name of this flag report stats
     */
    public String getClassName();

    /**
     * Returns the class name ID of this flag report stats.
     *
     * @return the class name ID of this flag report stats
     */
    public long getClassNameId();

    /**
     * Sets the class name ID of this flag report stats.
     *
     * @param classNameId the class name ID of this flag report stats
     */
    public void setClassNameId(long classNameId);

    /**
     * Returns the class p k of this flag report stats.
     *
     * @return the class p k of this flag report stats
     */
    public long getClassPK();

    /**
     * Sets the class p k of this flag report stats.
     *
     * @param classPK the class p k of this flag report stats
     */
    public void setClassPK(long classPK);

    /**
     * Returns the total entries of this flag report stats.
     *
     * @return the total entries of this flag report stats
     */
    public Integer getTotalEntries();

    /**
     * Sets the total entries of this flag report stats.
     *
     * @param totalEntries the total entries of this flag report stats
     */
    public void setTotalEntries(Integer totalEntries);

    /**
     * Returns the total moderated of this flag report stats.
     *
     * @return the total moderated of this flag report stats
     */
    public Integer getTotalModerated();

    /**
     * Sets the total moderated of this flag report stats.
     *
     * @param totalModerated the total moderated of this flag report stats
     */
    public void setTotalModerated(Integer totalModerated);

    /**
     * Returns the total approved of this flag report stats.
     *
     * @return the total approved of this flag report stats
     */
    public Integer getTotalApproved();

    /**
     * Sets the total approved of this flag report stats.
     *
     * @param totalApproved the total approved of this flag report stats
     */
    public void setTotalApproved(Integer totalApproved);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(FlagReportStats flagReportStats);

    public int hashCode();

    public CacheModel<FlagReportStats> toCacheModel();

    public FlagReportStats toEscapedModel();

    public String toString();

    public String toXmlString();
}
