package org.nterlearning.datamodel.catalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.nterlearning.datamodel.catalog.model.ExternalLink;
import org.nterlearning.datamodel.catalog.service.ExternalLinkLocalServiceUtil;

/**
 * The extended model base implementation for the ExternalLink service. Represents a row in the &quot;CATALOG_ExternalLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExternalLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExternalLinkImpl
 * @see org.nterlearning.datamodel.catalog.model.ExternalLink
 * @generated
 */
public abstract class ExternalLinkBaseImpl extends ExternalLinkModelImpl
    implements ExternalLink {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a external link model instance should use the {@link ExternalLink} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ExternalLinkLocalServiceUtil.addExternalLink(this);
        } else {
            ExternalLinkLocalServiceUtil.updateExternalLink(this);
        }
    }
}
