package org.nterlearning.datamodel.catalog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CourseRelated service. Represents a row in the &quot;CATALOG_CourseRelated&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.nterlearning.datamodel.catalog.model.impl.CourseRelatedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.nterlearning.datamodel.catalog.model.impl.CourseRelatedImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseRelated
 * @see org.nterlearning.datamodel.catalog.model.impl.CourseRelatedImpl
 * @see org.nterlearning.datamodel.catalog.model.impl.CourseRelatedModelImpl
 * @generated
 */
public interface CourseRelatedModel extends BaseModel<CourseRelated> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a course related model instance should use the {@link CourseRelated} interface instead.
     */

    /**
     * Returns the primary key of this course related.
     *
     * @return the primary key of this course related
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this course related.
     *
     * @param primaryKey the primary key of this course related
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the course related ID of this course related.
     *
     * @return the course related ID of this course related
     */
    public long getCourseRelatedId();

    /**
     * Sets the course related ID of this course related.
     *
     * @param courseRelatedId the course related ID of this course related
     */
    public void setCourseRelatedId(long courseRelatedId);

    /**
     * Returns the course ID of this course related.
     *
     * @return the course ID of this course related
     */
    public long getCourseId();

    /**
     * Sets the course ID of this course related.
     *
     * @param courseId the course ID of this course related
     */
    public void setCourseId(long courseId);

    /**
     * Returns the related course ID of this course related.
     *
     * @return the related course ID of this course related
     */
    public long getRelatedCourseId();

    /**
     * Sets the related course ID of this course related.
     *
     * @param relatedCourseId the related course ID of this course related
     */
    public void setRelatedCourseId(long relatedCourseId);

    /**
     * Returns the related course iri of this course related.
     *
     * @return the related course iri of this course related
     */
    @AutoEscape
    public String getRelatedCourseIri();

    /**
     * Sets the related course iri of this course related.
     *
     * @param relatedCourseIri the related course iri of this course related
     */
    public void setRelatedCourseIri(String relatedCourseIri);

    /**
     * Returns the relationship type of this course related.
     *
     * @return the relationship type of this course related
     */
    @AutoEscape
    public String getRelationshipType();

    /**
     * Sets the relationship type of this course related.
     *
     * @param relationshipType the relationship type of this course related
     */
    public void setRelationshipType(String relationshipType);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(CourseRelated courseRelated);

    public int hashCode();

    public CacheModel<CourseRelated> toCacheModel();

    public CourseRelated toEscapedModel();

    public String toString();

    public String toXmlString();
}
