package org.nterlearning.datamodel.catalog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CourseReview service. Represents a row in the &quot;CATALOG_CourseReview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.nterlearning.datamodel.catalog.model.impl.CourseReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.nterlearning.datamodel.catalog.model.impl.CourseReviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseReview
 * @see org.nterlearning.datamodel.catalog.model.impl.CourseReviewImpl
 * @see org.nterlearning.datamodel.catalog.model.impl.CourseReviewModelImpl
 * @generated
 */
public interface CourseReviewModel extends BaseModel<CourseReview> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a course review model instance should use the {@link CourseReview} interface instead.
     */

    /**
     * Returns the primary key of this course review.
     *
     * @return the primary key of this course review
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this course review.
     *
     * @param primaryKey the primary key of this course review
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the course review ID of this course review.
     *
     * @return the course review ID of this course review
     */
    public long getCourseReviewId();

    /**
     * Sets the course review ID of this course review.
     *
     * @param courseReviewId the course review ID of this course review
     */
    public void setCourseReviewId(long courseReviewId);

    /**
     * Returns the company ID of this course review.
     *
     * @return the company ID of this course review
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this course review.
     *
     * @param companyId the company ID of this course review
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this course review.
     *
     * @return the group ID of this course review
     */
    public long getGroupId();

    /**
     * Sets the group ID of this course review.
     *
     * @param groupId the group ID of this course review
     */
    public void setGroupId(long groupId);

    /**
     * Returns the course ID of this course review.
     *
     * @return the course ID of this course review
     */
    public long getCourseId();

    /**
     * Sets the course ID of this course review.
     *
     * @param courseId the course ID of this course review
     */
    public void setCourseId(long courseId);

    /**
     * Returns the user ID of this course review.
     *
     * @return the user ID of this course review
     */
    public long getUserId();

    /**
     * Sets the user ID of this course review.
     *
     * @param userId the user ID of this course review
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this course review.
     *
     * @return the user uuid of this course review
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this course review.
     *
     * @param userUuid the user uuid of this course review
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the summary of this course review.
     *
     * @return the summary of this course review
     */
    @AutoEscape
    public String getSummary();

    /**
     * Sets the summary of this course review.
     *
     * @param summary the summary of this course review
     */
    public void setSummary(String summary);

    /**
     * Returns the content of this course review.
     *
     * @return the content of this course review
     */
    @AutoEscape
    public String getContent();

    /**
     * Sets the content of this course review.
     *
     * @param content the content of this course review
     */
    public void setContent(String content);

    /**
     * Returns the create date of this course review.
     *
     * @return the create date of this course review
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this course review.
     *
     * @param createDate the create date of this course review
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this course review.
     *
     * @return the modified date of this course review
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this course review.
     *
     * @param modifiedDate the modified date of this course review
     */
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the weighted score of this course review.
     *
     * @return the weighted score of this course review
     */
    public double getWeightedScore();

    /**
     * Sets the weighted score of this course review.
     *
     * @param weightedScore the weighted score of this course review
     */
    public void setWeightedScore(double weightedScore);

    /**
     * Returns the removed of this course review.
     *
     * @return the removed of this course review
     */
    public boolean getRemoved();

    /**
     * Returns <code>true</code> if this course review is removed.
     *
     * @return <code>true</code> if this course review is removed; <code>false</code> otherwise
     */
    public boolean isRemoved();

    /**
     * Sets whether this course review is removed.
     *
     * @param removed the removed of this course review
     */
    public void setRemoved(boolean removed);

    /**
     * Returns the removed date of this course review.
     *
     * @return the removed date of this course review
     */
    public Date getRemovedDate();

    /**
     * Sets the removed date of this course review.
     *
     * @param removedDate the removed date of this course review
     */
    public void setRemovedDate(Date removedDate);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(CourseReview courseReview);

    public int hashCode();

    public CacheModel<CourseReview> toCacheModel();

    public CourseReview toEscapedModel();

    public String toString();

    public String toXmlString();
}
