package org.nterlearning.datamodel.catalog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FeedSyncHistory service. Represents a row in the &quot;CATALOG_FeedSyncHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.nterlearning.datamodel.catalog.model.impl.FeedSyncHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.nterlearning.datamodel.catalog.model.impl.FeedSyncHistoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FeedSyncHistory
 * @see org.nterlearning.datamodel.catalog.model.impl.FeedSyncHistoryImpl
 * @see org.nterlearning.datamodel.catalog.model.impl.FeedSyncHistoryModelImpl
 * @generated
 */
public interface FeedSyncHistoryModel extends BaseModel<FeedSyncHistory> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a feed sync history model instance should use the {@link FeedSyncHistory} interface instead.
     */

    /**
     * Returns the primary key of this feed sync history.
     *
     * @return the primary key of this feed sync history
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this feed sync history.
     *
     * @param primaryKey the primary key of this feed sync history
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the sync ID of this feed sync history.
     *
     * @return the sync ID of this feed sync history
     */
    public long getSyncId();

    /**
     * Sets the sync ID of this feed sync history.
     *
     * @param syncId the sync ID of this feed sync history
     */
    public void setSyncId(long syncId);

    /**
     * Returns the feed reference ID of this feed sync history.
     *
     * @return the feed reference ID of this feed sync history
     */
    public long getFeedReferenceId();

    /**
     * Sets the feed reference ID of this feed sync history.
     *
     * @param feedReferenceId the feed reference ID of this feed sync history
     */
    public void setFeedReferenceId(long feedReferenceId);

    /**
     * Returns the sync date of this feed sync history.
     *
     * @return the sync date of this feed sync history
     */
    public Date getSyncDate();

    /**
     * Sets the sync date of this feed sync history.
     *
     * @param syncDate the sync date of this feed sync history
     */
    public void setSyncDate(Date syncDate);

    /**
     * Returns the success of this feed sync history.
     *
     * @return the success of this feed sync history
     */
    public Boolean getSuccess();

    /**
     * Sets the success of this feed sync history.
     *
     * @param success the success of this feed sync history
     */
    public void setSuccess(Boolean success);

    /**
     * Returns the sync message of this feed sync history.
     *
     * @return the sync message of this feed sync history
     */
    @AutoEscape
    public String getSyncMessage();

    /**
     * Sets the sync message of this feed sync history.
     *
     * @param syncMessage the sync message of this feed sync history
     */
    public void setSyncMessage(String syncMessage);

    /**
     * Returns the number of entries of this feed sync history.
     *
     * @return the number of entries of this feed sync history
     */
    public Integer getNumberOfEntries();

    /**
     * Sets the number of entries of this feed sync history.
     *
     * @param numberOfEntries the number of entries of this feed sync history
     */
    public void setNumberOfEntries(Integer numberOfEntries);

    public boolean isNew();

    public void setNew(boolean n);

    public boolean isCachedModel();

    public void setCachedModel(boolean cachedModel);

    public boolean isEscapedModel();

    public Serializable getPrimaryKeyObj();

    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    public ExpandoBridge getExpandoBridge();

    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public Object clone();

    public int compareTo(FeedSyncHistory feedSyncHistory);

    public int hashCode();

    public CacheModel<FeedSyncHistory> toCacheModel();

    public FeedSyncHistory toEscapedModel();

    public String toString();

    public String toXmlString();
}
