package org.nterlearning.datamodel.catalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.nterlearning.datamodel.catalog.model.ComponentRecord;
import org.nterlearning.datamodel.catalog.service.ComponentRecordLocalServiceUtil;

/**
 * The extended model base implementation for the ComponentRecord service. Represents a row in the &quot;CATALOG_ComponentRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ComponentRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ComponentRecordImpl
 * @see org.nterlearning.datamodel.catalog.model.ComponentRecord
 * @generated
 */
public abstract class ComponentRecordBaseImpl extends ComponentRecordModelImpl
    implements ComponentRecord {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a component record model instance should use the {@link ComponentRecord} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ComponentRecordLocalServiceUtil.addComponentRecord(this);
        } else {
            ComponentRecordLocalServiceUtil.updateComponentRecord(this);
        }
    }
}
