package org.nterlearning.datamodel.catalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.nterlearning.datamodel.catalog.model.Contributor;
import org.nterlearning.datamodel.catalog.service.ContributorLocalServiceUtil;

/**
 * The extended model base implementation for the Contributor service. Represents a row in the &quot;CATALOG_Contributor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContributorImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContributorImpl
 * @see org.nterlearning.datamodel.catalog.model.Contributor
 * @generated
 */
public abstract class ContributorBaseImpl extends ContributorModelImpl
    implements Contributor {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a contributor model instance should use the {@link Contributor} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            ContributorLocalServiceUtil.addContributor(this);
        } else {
            ContributorLocalServiceUtil.updateContributor(this);
        }
    }
}
