package org.nterlearning.datamodel.catalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.nterlearning.datamodel.catalog.model.Courses_Components;
import org.nterlearning.datamodel.catalog.service.Courses_ComponentsLocalServiceUtil;

/**
 * The extended model base implementation for the Courses_Components service. Represents a row in the &quot;CATALOG_Courses_Components&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Courses_ComponentsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Courses_ComponentsImpl
 * @see org.nterlearning.datamodel.catalog.model.Courses_Components
 * @generated
 */
public abstract class Courses_ComponentsBaseImpl
    extends Courses_ComponentsModelImpl implements Courses_Components {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a courses_ components model instance should use the {@link Courses_Components} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            Courses_ComponentsLocalServiceUtil.addCourses_Components(this);
        } else {
            Courses_ComponentsLocalServiceUtil.updateCourses_Components(this);
        }
    }
}
