package org.nterlearning.datamodel.catalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.nterlearning.datamodel.catalog.model.FlagReportStats;
import org.nterlearning.datamodel.catalog.service.FlagReportStatsLocalServiceUtil;

/**
 * The extended model base implementation for the FlagReportStats service. Represents a row in the &quot;CATALOG_FlagReportStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FlagReportStatsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FlagReportStatsImpl
 * @see org.nterlearning.datamodel.catalog.model.FlagReportStats
 * @generated
 */
public abstract class FlagReportStatsBaseImpl extends FlagReportStatsModelImpl
    implements FlagReportStats {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a flag report stats model instance should use the {@link FlagReportStats} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            FlagReportStatsLocalServiceUtil.addFlagReportStats(this);
        } else {
            FlagReportStatsLocalServiceUtil.updateFlagReportStats(this);
        }
    }
}
