package org.nterlearning.datamodel.catalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.nterlearning.datamodel.catalog.model.GlobalCourseReview;
import org.nterlearning.datamodel.catalog.service.GlobalCourseReviewLocalServiceUtil;

/**
 * The extended model base implementation for the GlobalCourseReview service. Represents a row in the &quot;CATALOG_GlobalCourseReview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GlobalCourseReviewImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GlobalCourseReviewImpl
 * @see org.nterlearning.datamodel.catalog.model.GlobalCourseReview
 * @generated
 */
public abstract class GlobalCourseReviewBaseImpl
    extends GlobalCourseReviewModelImpl implements GlobalCourseReview {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a global course review model instance should use the {@link GlobalCourseReview} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            GlobalCourseReviewLocalServiceUtil.addGlobalCourseReview(this);
        } else {
            GlobalCourseReviewLocalServiceUtil.updateGlobalCourseReview(this);
        }
    }
}
